topic_col = ['digitalization_green_transition_and_recovery', 
             'climate_energy_and_sustainability', 
             'healthcare_funding',
             'storify',
             'citizens_initiatives',
             'common_market_and_eu_law',
             'infographics',
             'post_summit_statements',
             'humanitarian_support',
             'strategic_investments', 
             'vaccines',
             'culture_history_and_values',
             'presidential_addresses',
             'finance',
             'citizens_rights',
             'live_events',
             'institutional_statements',
             'consumer_rights_and_digital_policy',
             'future_of_the_eu',
             'eu_commission_announcements']

exclude_col = ['presidential_addresses',
               'infographics', 
               'post_summit_statements',
               'live_events',
               'storify',
               'institutional_statements', 
               'eu_commission_announcements'] 

emotion_col = ['negative_sentiment', 'positive_sentiment', 'neutral_sentiment']

style_col = ['flesch_reading_ease', 'flesch_kincaid_grade', 'smog', 'gunning_fog',
             'automated_readability_index', 'coleman_liau_index', 'lix', 'rix',
             'dependency_distance_mean', 'dependency_distance_std',
             'prop_adjacent_dependency_relation_mean',
             'prop_adjacent_dependency_relation_std', 'token_length_mean',
             'token_length_median', 'token_length_std', 'sentence_length_mean',
             'sentence_length_median', 'sentence_length_std',
             'syllables_per_token_mean', 'syllables_per_token_median',
             'syllables_per_token_std', 'n_tokens', 'n_unique_tokens',
             'proportion_unique_tokens', 'n_characters', 'n_sentences',
             'n_stop_words', 'alpha_ratio', 'mean_word_length', 'doc_length',
             'proportion_ellipsis', 'proportion_bullet_points',
             'duplicate_line_chr_fraction', 'duplicate_paragraph_chr_fraction',
             'duplicate_5-gram_chr_fraction', 'duplicate_6-gram_chr_fraction',
             'duplicate_7-gram_chr_fraction', 'duplicate_8-gram_chr_fraction',
             'duplicate_9-gram_chr_fraction', 'duplicate_10-gram_chr_fraction',
             'top_2-gram_chr_fraction', 'top_3-gram_chr_fraction',
             'top_4-gram_chr_fraction', 'symbol_#_2_word_ratio',
             'contains_lorem ipsum', 'pos_prop_NUM', 'pos_prop_NOUN', 'pos_prop_ADJ',
             'pos_prop_ADP', 'pos_prop_DET', 'pos_prop_PROPN', 'pos_prop_ADV',
             'pos_prop_SYM', 'pos_prop_PUNCT', 'pos_prop_SCONJ', 'pos_prop_PRON',
             'pos_prop_VERB', 'pos_prop_X',
             'pos_prop_AUX', 'pos_prop_CCONJ', 'pos_prop_SPACE', 'pos_prop_PART',
             'pos_prop_INTJ', 'subtlexusfrequency_SUBTLWF', 
             'subtlexusfrequency_Lg10WF', 'subtlexusfrequency_Zipf-value']

pca_col = [f'style_dim_{i}' for i in range(len(style_col))]