topic_col = ['Solidarity and Emergency Response',
             'Health',
             'Citizen Initiatives',
             'Press conferences and Statements',
             'Citizen Rights and Integration',
             'Charts, Links, Infographics',
             'Strategic Investments (e.g., recovery, research, innovation)',
             'Internal Governance',
             'Energy, Sustainability and Climate',
             'Identity, Culture and Citizen Engagement',
             'Visions for the Future',
             'Financial Aid',
             'Human Rights',
             'Growth and Global Development',
             'Economy and markets',
             'Digital Policy',
             'Trade, Partnerships, and Law',
             'Live Events',
             'Digital and Green Transition',
             'Finance and trade']

style_col = ['concreteness',
             'reading complexity',
             'verb-to-noun ratio',
             'tweet length',
             'sentence length',
             'word length',
             'frequency',
             'negative sentiment', 'neutral sentiment', 'positive sentiment',
             '% hashtag', 
             '% mentions', 
             '% emojis']
